/**
 * 衣橱各品类「底库存」：保证每类至少约 30 套可展示。
 * 与各角色的 outfit.json 合并时去重补齐。
 */

export const STOCK_DRESSES = [
  { id: 'd_therow_wool_black', label: 'The Row 黑色羊毛连衣裙', brand: 'The Row', kind: 'knit' },
  { id: 'd_ysl_black_bodycon', label: 'Saint Laurent 黑色修身礼服裙', brand: 'Saint Laurent', kind: 'evening' },
  { id: 'd_dior_structured', label: 'Dior 结构感连衣裙', brand: 'Dior', kind: 'other' },
  { id: 'd_silk_slip_sleep', label: '真丝吊带睡裙', brand: 'Olivia von Halle', kind: 'satin' },
  { id: 'd_couture_evening', label: '深色高级定制晚礼服（结构利落）', brand: '', kind: 'evening' },
  { id: 'd_therow_linen_summer', label: 'The Row 亚麻/真丝夏裙', brand: 'The Row', kind: 'other' },
  { id: 'd_wine_velvet', label: '深酒红丝绒修身长裙（细肩带）', brand: '', kind: 'evening' },
  { id: 'd_champagne_bias', label: '香槟真丝 bias-cut 吊带长裙', brand: 'The Row', kind: 'satin' },
  { id: 'd_black_bias_ankle', label: '黑色真丝斜裁及踝裙', brand: '', kind: 'satin' },
  { id: 'd_green_cashmere_knit', label: '墨绿羊绒针织连衣裙', brand: 'Loro Piana', kind: 'knit' },
  { id: 'd_black_turtleneck_knit', label: '黑色高领修身针织长裙', brand: 'The Row', kind: 'knit' },
  { id: 'd_forest_crepe', label: '深墨绿真丝绉纱直筒长裙', brand: '', kind: 'satin' },
  { id: 'd_warm_grey_knit', label: '暖灰色修身针织连衣长裙（方领）', brand: '', kind: 'knit' },
  { id: 'd_wine_wrap', label: '深酒红色裹身式连衣裙（哑光缎面）', brand: '', kind: 'wrap' },
  { id: 'd_lavender_satin', label: '低饱和紫灰色丝缎收腰长裙', brand: '', kind: 'satin' },
  { id: 'd_navy_qipao', label: '深蓝灰色改良旗袍式连衣裙', brand: '', kind: 'qipao' },
  { id: 'd_ink_green_suit', label: '低饱和墨绿收腰西装裙', brand: 'The Row', kind: 'suit' },
  { id: 'd_black_knit_evening', label: '黑色修身长袖针织连衣裙', brand: '', kind: 'knit' },
  { id: 'd_celine_black_midi', label: 'Celine 黑色中长连衣裙', brand: 'Celine', kind: 'other' },
  { id: 'd_toteme_wrap_beige', label: 'Totême 米色裹身长裙', brand: 'Totême', kind: 'wrap' },
  { id: 'd_khaite_black_rib', label: 'Khaite 黑色罗纹针织裙', brand: 'Khaite', kind: 'knit' },
  { id: 'd_gabriela_hearst_ivory', label: 'Gabriela Hearst 象牙白羊毛裙', brand: 'Gabriela Hearst', kind: 'other' },
  { id: 'd_jil_sander_column', label: 'Jil Sander 极简柱形长裙', brand: 'Jil Sander', kind: 'other' },
  { id: 'd_lemaire_soft_grey', label: 'Lemaire 软灰垂坠连衣裙', brand: 'Lemaire', kind: 'other' },
  { id: 'd_bottega_leather_mini', label: 'Bottega Veneta 皮质迷你裙装感连衣裙', brand: 'Bottega Veneta', kind: 'other' },
  { id: 'd_chanel_tweed_shift', label: 'Chanel 花呢直筒裙', brand: 'Chanel', kind: 'other' },
  { id: 'd_dior_bar_midi', label: 'Dior Bar 中长裙轮廓连衣裙', brand: 'Dior', kind: 'suit' },
  { id: 'd_prada_nylon_tech', label: 'Prada 科技感尼龙连衣裙', brand: 'Prada', kind: 'other' },
  { id: 'd_valentino_red_crepe', label: 'Valentino 正红绉纱中长裙', brand: 'Valentino', kind: 'evening' },
  { id: 'd_alaia_bandage_black', label: 'Alaïa 黑色绷带修身裙', brand: 'Alaïa', kind: 'other' },
  { id: 'd_issey_pleats_grey', label: 'Issey Miyake 褶皱灰裙', brand: 'Issey Miyake', kind: 'other' },
  { id: 'd_acne_soft_black', label: 'Acne Studios 软黑直筒裙', brand: 'Acne Studios', kind: 'other' },
];

export const STOCK_TOPS = [
  { id: 't_hermes_silk_white', label: 'Hermès 白色丝质衬衫', brand: 'Hermès', kind: 'shirt' },
  { id: 't_therow_white_tee', label: 'The Row 白棉 T', brand: 'The Row', kind: 'tee' },
  { id: 't_loro_cashmere_camel', label: 'Loro Piana 驼色羊绒上衣', brand: 'Loro Piana', kind: 'knit' },
  { id: 't_his_white_shirt', label: '他的白衬衫', brand: '', kind: 'shirt' },
  { id: 't_therow_silk_ivory', label: 'The Row 象牙白真丝衬衫', brand: 'The Row', kind: 'blouse' },
  { id: 't_celine_black_shirt', label: 'Celine 黑色宽松衬衫', brand: 'Celine', kind: 'shirt' },
  { id: 't_khaite_cream_knit', label: 'Khaite 奶油色贴身高领针织', brand: 'Khaite', kind: 'knit' },
  { id: 't_brunello_soft_tee', label: 'Brunello Cucinelli 软棉上衣', brand: 'Brunello Cucinelli', kind: 'tee' },
  { id: 't_toteme_stripe_shirt', label: 'Totême 细条纹衬衫', brand: 'Totême', kind: 'shirt' },
  { id: 't_jil_sander_poplin', label: 'Jil Sander 府绸白衬衫', brand: 'Jil Sander', kind: 'shirt' },
  { id: 't_lemaire_soft_blouse', label: 'Lemaire 软垂真丝罩衫', brand: 'Lemaire', kind: 'blouse' },
  { id: 't_bottega_leather_top', label: 'Bottega Veneta 皮质短上衣', brand: 'Bottega Veneta', kind: 'other' },
  { id: 't_chanel_cc_tee', label: 'Chanel 双C 简约上衣', brand: 'Chanel', kind: 'tee' },
  { id: 't_dior_bar_blouse', label: 'Dior 结构感上衣', brand: 'Dior', kind: 'blouse' },
  { id: 't_ysl_silk_black', label: 'Saint Laurent 黑色真丝衬衫', brand: 'Saint Laurent', kind: 'shirt' },
  { id: 't_prada_nylon_top', label: 'Prada 尼龙轻薄上衣', brand: 'Prada', kind: 'other' },
  { id: 't_maxmara_wool_turtleneck', label: 'Max Mara 羊毛高领', brand: 'Max Mara', kind: 'knit' },
  { id: 't_therow_cashmere_crew', label: 'The Row 羊绒圆领衫', brand: 'The Row', kind: 'knit' },
  { id: 't_hermes_twill_shirt', label: 'Hermès 斜纹真丝衬衫', brand: 'Hermès', kind: 'blouse' },
  { id: 't_loro_summer_linen', label: 'Loro Piana 亚麻轻薄上衣', brand: 'Loro Piana', kind: 'blouse' },
  { id: 't_gabriela_sculpt_top', label: 'Gabriela Hearst 雕塑感上衣', brand: 'Gabriela Hearst', kind: 'other' },
  { id: 't_acne_soft_crew', label: 'Acne Studios 软圆领', brand: 'Acne Studios', kind: 'tee' },
  { id: 't_cos_merino', label: '极简美丽诺羊毛上衣', brand: '', kind: 'knit' },
  { id: 't_silk_camisole_nude', label: '裸色真丝吊带背心', brand: '', kind: 'blouse' },
  { id: 't_black_turtleneck_fine', label: '黑色细针织高领', brand: 'The Row', kind: 'knit' },
  { id: 't_white_poplin_french', label: '法式泡泡袖白衬衫（克制版）', brand: '', kind: 'shirt' },
  { id: 't_grey_merino_v', label: '烟灰美丽诺 V 领', brand: 'Loro Piana', kind: 'knit' },
  { id: 't_navy_silk_shell', label: '海军蓝真丝无袖上衣', brand: '', kind: 'blouse' },
  { id: 't_camel_cashmere_shell', label: '驼色羊绒无袖上衣', brand: 'Loro Piana', kind: 'knit' },
  { id: 't_stripe_breton_soft', label: '软海魂条纹上衣（高级棉）', brand: '', kind: 'tee' },
  { id: 't_satin_champagne_blouse', label: '香槟缎面上衣', brand: '', kind: 'blouse' },
  { id: 't_work_white_poplin', label: '职场白府绸衬衫', brand: 'The Row', kind: 'shirt' },
];

export const STOCK_BOTTOMS = [
  { id: 'b_therow_black_trouser', label: 'The Row 黑色直筒西裤', brand: 'The Row', kind: 'trousers' },
  { id: 'b_brunello_dark_trouser', label: 'Brunello Cucinelli 深色西裤', brand: 'Brunello Cucinelli', kind: 'trousers' },
  { id: 'b_loro_soft_pant', label: 'Loro Piana 柔软休闲长裤', brand: 'Loro Piana', kind: 'casual' },
  { id: 'b_celine_wide_leg', label: 'Celine 黑色阔腿西裤', brand: 'Celine', kind: 'trousers' },
  { id: 'b_toteme_pleat', label: 'Totême 压褶长裤', brand: 'Totême', kind: 'trousers' },
  { id: 'b_jil_sander_column', label: 'Jil Sander 柱形长裤', brand: 'Jil Sander', kind: 'trousers' },
  { id: 'b_lemaire_soft_pant', label: 'Lemaire 软垂长裤', brand: 'Lemaire', kind: 'casual' },
  { id: 'b_khaite_leather_pant', label: 'Khaite 皮质长裤', brand: 'Khaite', kind: 'other' },
  { id: 'b_therow_ivory_trouser', label: 'The Row 米白西裤', brand: 'The Row', kind: 'trousers' },
  { id: 'b_maxmara_camel_pant', label: 'Max Mara 驼色长裤', brand: 'Max Mara', kind: 'trousers' },
  { id: 'b_ysl_cigarette', label: 'Saint Laurent 烟管裤', brand: 'Saint Laurent', kind: 'trousers' },
  { id: 'b_dior_wide', label: 'Dior 高腰阔腿裤', brand: 'Dior', kind: 'trousers' },
  { id: 'b_chanel_tweed_pant', label: 'Chanel 花呢长裤', brand: 'Chanel', kind: 'trousers' },
  { id: 'b_prada_nylon_pant', label: 'Prada 尼龙工装感长裤', brand: 'Prada', kind: 'casual' },
  { id: 'b_acne_soft_denim', label: 'Acne Studios 软牛仔', brand: 'Acne Studios', kind: 'casual' },
  { id: 'b_pencil_grey', label: '深灰高腰半身裙', brand: '', kind: 'skirt' },
  { id: 'b_pencil_black', label: '黑色包臀半身裙', brand: '', kind: 'skirt' },
  { id: 'b_a_line_camel', label: '驼色 A 字半身裙', brand: 'Max Mara', kind: 'skirt' },
  { id: 'b_pleat_midi', label: '压褶中长半身裙', brand: 'Totême', kind: 'skirt' },
  { id: 'b_silk_bias_skirt', label: '真丝斜裁半身裙', brand: '', kind: 'skirt' },
  { id: 'b_home_cashmere_pant', label: '羊绒家居长裤', brand: 'Loro Piana', kind: 'casual' },
  { id: 'b_sport_legging', label: 'Lululemon 深色紧身裤', brand: 'Lululemon', kind: 'casual' },
  { id: 'b_tailored_navy', label: '海军蓝量体西裤', brand: 'The Row', kind: 'trousers' },
  { id: 'b_cream_wide', label: '奶油色阔腿裤', brand: 'The Row', kind: 'trousers' },
  { id: 'b_charcoal_slim', label: '炭灰修身西裤', brand: 'Brunello Cucinelli', kind: 'trousers' },
  { id: 'b_olive_utility', label: '橄榄绿工装休闲裤', brand: '', kind: 'casual' },
  { id: 'b_satin_slip_skirt', label: '缎面吊带式半身裙', brand: '', kind: 'skirt' },
  { id: 'b_wool_midi_black', label: '黑色羊毛中长半身裙', brand: 'The Row', kind: 'skirt' },
  { id: 'b_leather_mini_skirt', label: '黑色皮质迷你裙（克制版）', brand: 'Saint Laurent', kind: 'skirt' },
  { id: 'b_palazzo_cream', label: '奶油色阔腿宫装裤', brand: 'Loro Piana', kind: 'trousers' },
  { id: 'b_tech_soft_pant', label: '科技面料软长裤', brand: 'Prada', kind: 'casual' },
];

export const STOCK_HAIR = [
  { id: 'h_low_ponytail', label: '长发低马尾', kind: 'ponytail' },
  { id: 'h_high_ponytail', label: '高马尾', kind: 'ponytail' },
  { id: 'h_loose_updo', label: '松散低盘发', kind: 'updo' },
  { id: 'h_low_chignon', label: '低发髻', kind: 'updo' },
  { id: 'h_air_waves', label: '空气感大波浪', kind: 'waves' },
  { id: 'h_soft_curls', label: '半扎长卷发', kind: 'waves' },
  { id: 'h_straight_mid', label: '顺直中长发（发尾内扣）', kind: 'down' },
  { id: 'h_center_part_down', label: '中分披肩长发', kind: 'down' },
  { id: 'h_side_part_soft', label: '侧分柔和披发', kind: 'down' },
  { id: 'h_messy_soft', label: '微乱披肩', kind: 'down' },
  { id: 'h_sleep_loose', label: '披散随意', kind: 'down' },
  { id: 'h_wet_slick', label: '湿发后梳（克制）', kind: 'other' },
  { id: 'h_french_twist', label: '法式扭转盘发', kind: 'updo' },
  { id: 'h_braid_soft', label: '松软低编发', kind: 'other' },
  { id: 'h_half_up', label: '半扎半披', kind: 'other' },
  { id: 'h_bob_soft', label: '柔和锁骨发', kind: 'down' },
  { id: 'h_curtain_bang', label: '帘幕刘海长发', kind: 'down' },
  { id: 'h_no_bang_long', label: '无刘海长直发', kind: 'down' },
  { id: 'h_volume_root', label: '根部微蓬披发', kind: 'down' },
  { id: 'h_slick_pony', label: '服帖低马尾', kind: 'ponytail' },
  { id: 'h_bubble_pony', label: '泡泡马尾（克制版）', kind: 'ponytail' },
  { id: 'h_twist_up', label: '双股扭转盘', kind: 'updo' },
  { id: 'h_hollywood_waves', label: '复古大波浪', kind: 'waves' },
  { id: 'h_beach_wave', label: '慵懒沙滩卷', kind: 'waves' },
  { id: 'h_blowout', label: '沙龙吹风卷', kind: 'waves' },
  { id: 'h_pin_curl_soft', label: '软发夹固定造型', kind: 'updo' },
  { id: 'h_top_knot_soft', label: '松软丸子头', kind: 'updo' },
  { id: 'h_side_sweep', label: '侧扫披肩', kind: 'down' },
  { id: 'h_elegant_chignon', label: '晚宴低髻', kind: 'updo' },
  { id: 'h_natural_flyaway', label: '自然碎发披肩', kind: 'down' },
  { id: 'h_work_slick', label: '职场服帖中分', kind: 'down' },
];

export const STOCK_OUTERWEAR = [
  { id: 'o_maxmara_101801', label: 'Max Mara 经典驼大衣 101801', brand: 'Max Mara', kind: 'coat' },
  { id: 'o_therow_long_black', label: 'The Row 长款黑大衣', brand: 'The Row', kind: 'coat' },
  { id: 'o_celine_long', label: 'Celine 长款大衣', brand: 'Celine', kind: 'coat' },
  { id: 'o_loro_cashmere_coat', label: 'Loro Piana 羊绒大衣', brand: 'Loro Piana', kind: 'coat' },
  { id: 'o_bottega_leather', label: 'Bottega Veneta 皮外套', brand: 'Bottega Veneta', kind: 'leather' },
  { id: 'o_therow_blazer_black', label: 'The Row 黑色西装外套', brand: 'The Row', kind: 'blazer' },
  { id: 'o_loro_cardigan_camel', label: 'Loro Piana 驼羊绒开衫', brand: 'Loro Piana', kind: 'knit' },
  { id: 'o_ovh_robe', label: 'Olivia von Halle 丝质晨袍', brand: 'Olivia von Halle', kind: 'knit' },
  { id: 'o_maxmara_teddy', label: 'Max Mara 泰迪大衣（短款）', brand: 'Max Mara', kind: 'coat' },
  { id: 'o_therow_cashmere_wrap', label: 'The Row 羊绒大披肩', brand: 'The Row', kind: 'knit' },
  { id: 'o_ysl_leather_blazer', label: 'Saint Laurent 皮西装', brand: 'Saint Laurent', kind: 'leather' },
  { id: 'o_dior_bar_jacket', label: 'Dior Bar 夹克', brand: 'Dior', kind: 'blazer' },
  { id: 'o_chanel_tweed_jacket', label: 'Chanel 花呢外套', brand: 'Chanel', kind: 'blazer' },
  { id: 'o_prada_nylon_coat', label: 'Prada 尼龙风衣', brand: 'Prada', kind: 'coat' },
  { id: 'o_burberry_trench', label: 'Burberry 经典风衣', brand: 'Burberry', kind: 'coat' },
  { id: 'o_toteme_scarf_coat', label: 'Totême 围巾领大衣', brand: 'Totême', kind: 'coat' },
  { id: 'o_khaite_leather_moto', label: 'Khaite 机车皮衣（克制）', brand: 'Khaite', kind: 'leather' },
  { id: 'o_brunello_knit_blazer', label: 'Brunello 针织西装外套', brand: 'Brunello Cucinelli', kind: 'blazer' },
  { id: 'o_jil_sander_coat', label: 'Jil Sander 极简大衣', brand: 'Jil Sander', kind: 'coat' },
  { id: 'o_lemaire_soft_coat', label: 'Lemaire 软廓形外套', brand: 'Lemaire', kind: 'coat' },
  { id: 'o_acne_wool_coat', label: 'Acne Studios 羊毛大衣', brand: 'Acne Studios', kind: 'coat' },
  { id: 'o_hermes_cashmere_shawl', label: 'Hermès 羊绒大披肩', brand: 'Hermès', kind: 'knit' },
  { id: 'o_cream_cardigan_short', label: '奶油色短款羊绒开衫', brand: 'Loro Piana', kind: 'knit' },
  { id: 'o_lavender_sheer_cardigan', label: '浅灰紫薄开衫', brand: '', kind: 'knit' },
  { id: 'o_beige_knit_shawl', label: '米杏色薄针织披肩', brand: '', kind: 'knit' },
  { id: 'o_navy_blazer', label: '海军蓝修身西装外套', brand: 'The Row', kind: 'blazer' },
  { id: 'o_camel_double_breasted', label: '驼色双排扣大衣', brand: 'Max Mara', kind: 'coat' },
  { id: 'o_black_cropped_blazer', label: '黑色短款西装', brand: 'Saint Laurent', kind: 'blazer' },
  { id: 'o_silk_kimono_robe', label: '真丝和风晨袍', brand: '', kind: 'knit' },
  { id: 'o_tech_softshell', label: '科技面料软壳外套', brand: 'Lululemon', kind: 'other' },
  { id: 'o_ivory_trench', label: '米白风衣', brand: 'The Row', kind: 'coat' },
];

export const STOCK_SHOES = [
  { id: 's_manolo_hangisi', label: 'Manolo Blahnik Hangisi 黑缎细跟', brand: 'Manolo Blahnik', kind: 'heel', heel: '细高跟' },
  { id: 's_louboutin_so_kate', label: 'Christian Louboutin So Kate 黑红底', brand: 'Christian Louboutin', kind: 'heel', heel: '细高跟' },
  { id: 's_jc_pump_black', label: 'Jimmy Choo 黑色经典细跟', brand: 'Jimmy Choo', kind: 'heel' },
  { id: 's_chanel_slingback', label: 'Chanel 双C 拼色 Slingback', brand: 'Chanel', kind: 'heel', heel: '中细跟' },
  { id: 's_dior_jadior', label: "Dior J'Adior 丝带低跟", brand: 'Dior', kind: 'flat' },
  { id: 's_hermes_oran', label: 'Hermès Oran 凉鞋 H扣', brand: 'Hermès', kind: 'sandal' },
  { id: 's_loro_summer_walk', label: 'Loro Piana Summer Walk 乐福', brand: 'Loro Piana', kind: 'loafer' },
  { id: 's_therow_loafer', label: 'The Row 简约乐福', brand: 'The Row', kind: 'loafer' },
  { id: 's_chanel_ballet', label: 'Chanel 双C 芭蕾平底', brand: 'Chanel', kind: 'flat' },
  { id: 's_therow_ankle_boot', label: 'The Row 短靴', brand: 'The Row', kind: 'boot' },
  { id: 's_hermes_kelly_boot', label: 'Hermès 短靴（Kelly 扣）', brand: 'Hermès', kind: 'boot' },
  { id: 's_cp_white', label: 'Common Projects Achilles 小白鞋', brand: 'Common Projects', kind: 'sneaker' },
  { id: 's_nude_kitten', label: '裸米色尖头小猫跟鞋', brand: '', kind: 'heel', heel: '小猫跟' },
  { id: 's_black_stiletto', label: '黑色尖头细跟高跟鞋', brand: 'Jimmy Choo', kind: 'heel' },
  { id: 's_grey_stiletto', label: '深灰色细跟高跟鞋', brand: '', kind: 'heel' },
  { id: 's_silver_strappy', label: '银灰色细带高跟凉鞋', brand: '', kind: 'sandal' },
  { id: 's_mary_jane_black', label: '黑色玛丽珍细跟鞋', brand: 'Chanel', kind: 'heel' },
  { id: 's_mule_ivory', label: '米白色穆勒高跟鞋', brand: '', kind: 'mule' },
  { id: 's_patent_black', label: '黑色漆皮尖头高跟鞋', brand: 'Louboutin', kind: 'heel' },
  { id: 's_black_strappy_sandal', label: '黑色细带高跟凉鞋', brand: '', kind: 'sandal' },
  { id: 's_chanel_low_black', label: 'Chanel 黑色低跟皮鞋', brand: 'Chanel', kind: 'heel', heel: '低跟' },
  { id: 's_manolo_low', label: 'Manolo Blahnik 低细跟', brand: 'Manolo Blahnik', kind: 'heel' },
  { id: 's_loro_slipper', label: 'Loro Piana 家居拖鞋', brand: 'Loro Piana', kind: 'flat' },
  { id: 's_nike_run', label: 'Nike 限定跑鞋', brand: 'Nike', kind: 'sneaker' },
  { id: 's_bottega_puddle', label: 'Bottega Veneta Puddle 雨靴感', brand: 'Bottega Veneta', kind: 'boot' },
  { id: 's_therow_boot_tall', label: 'The Row 高筒靴', brand: 'The Row', kind: 'boot' },
  { id: 's_gucci_loafer', label: 'Gucci 马衔扣乐福（克制）', brand: 'Gucci', kind: 'loafer' },
  { id: 's_roger_vivier_buckle', label: 'Roger Vivier 方扣平底', brand: 'Roger Vivier', kind: 'flat' },
  { id: 's_aquazzura_bow', label: 'Aquazzura 蝴蝶结细跟', brand: 'Aquazzura', kind: 'heel' },
  { id: 's_gianvito_nude', label: 'Gianvito Rossi 裸色细跟', brand: 'Gianvito Rossi', kind: 'heel' },
  { id: 's_celine_bootie', label: 'Celine 短靴', brand: 'Celine', kind: 'boot' },
];

export const STOCK_BAGS = [
  'Hermès Birkin 25 黑金 Togo',
  'Hermès Birkin 30 大象灰',
  'Hermès Kelly 28 外缝',
  'Hermès Kelly 25 内缝',
  'Hermès Constance',
  'Hermès Picotin 18',
  'Chanel Classic Flap 中号黑金',
  'Chanel Classic Flap 小号',
  'Chanel 22 黑银',
  'Chanel Boy 旧中号',
  'Chanel 19 小号',
  'Dior Lady Dior 中号',
  'Dior Book Tote 老花',
  'Dior Saddle 马鞍包',
  'Bottega Veneta Jodie 黄油白',
  'Bottega Veneta Cassette',
  'The Row Margaux 15',
  'The Row Margaux 10',
  'Celine Triomphe 中号',
  'Celine Ava',
  'Saint Laurent Lou Camera',
  'Saint Laurent Kate',
  'Loewe Puzzle 迷你',
  'Loewe Flamenco',
  'Loro Piana Extra Pocket L19',
  'Goyard Saint Louis PM',
  'Fendi Baguette',
  'Prada Re-Edition 尼龙',
  'Gucci Jackie 1961',
  'Balenciaga City（小）',
  'Givenchy Antigona 迷你',
];

export const STOCK_JEWELRY = [
  { id: 'j_cartier_love_narrow', label: 'Cartier 窄版 LOVE 手镯', brand: 'Cartier', kind: 'bracelet' },
  { id: 'j_cartier_juste', label: 'Cartier Juste un Clou 手镯', brand: 'Cartier', kind: 'bracelet' },
  { id: 'j_vca_alhambra_ear', label: 'Van Cleef 白金四叶草耳钉', brand: 'Van Cleef', kind: 'earring' },
  { id: 'j_vca_alhambra_neck', label: 'Van Cleef 四叶草项链', brand: 'Van Cleef', kind: 'necklace' },
  { id: 'j_diamond_stud', label: '小巧钻石耳钉', brand: '', kind: 'earring' },
  { id: 'j_pearl_stud', label: 'Akoya 珍珠耳钉', brand: '', kind: 'earring' },
  { id: 'j_cartier_trinity', label: 'Cartier Trinity 戒指', brand: 'Cartier', kind: 'ring' },
  { id: 'j_cartier_love_ring', label: 'Cartier LOVE 戒指', brand: 'Cartier', kind: 'ring' },
  { id: 'j_tiffany_t', label: 'Tiffany T 微笑项链', brand: 'Tiffany', kind: 'necklace' },
  { id: 'j_bvlgari_bzero', label: 'Bvlgari B.zero1 戒指', brand: 'Bvlgari', kind: 'ring' },
  { id: 'j_hermes_clic', label: 'Hermès Clic H 手镯', brand: 'Hermès', kind: 'bracelet' },
  { id: 'j_messika_move', label: 'Messika Move 手链', brand: 'Messika', kind: 'bracelet' },
  { id: 'j_piaget_possession', label: 'Piaget Possession 戒指', brand: 'Piaget', kind: 'ring' },
  { id: 'j_chaumet_bee', label: 'Chaumet 蜂巢耳钉', brand: 'Chaumet', kind: 'earring' },
  { id: 'j_gold_hoop_thin', label: '细圈金耳环', brand: '', kind: 'earring' },
  { id: 'j_diamond_tennis', label: '网球手链（细）', brand: '', kind: 'bracelet' },
  { id: 'j_solitaire_simple', label: '简约单钻项链', brand: '', kind: 'necklace' },
  { id: 'j_layered_gold', label: '双层细金链', brand: '', kind: 'necklace' },
  { id: 'j_cuff_soft', label: '软开口金手镯', brand: '', kind: 'bracelet' },
  { id: 'j_signet_minimal', label: '极简印戒', brand: '', kind: 'ring' },
  { id: 'j_drop_diamond', label: '水滴钻耳坠（小）', brand: '', kind: 'earring' },
  { id: 'j_jade_safety', label: '和田玉平安扣（低调）', brand: '', kind: 'necklace' },
  { id: 'j_cartier_clash', label: 'Cartier Clash 手镯', brand: 'Cartier', kind: 'bracelet' },
  { id: 'j_vca_perlée', label: 'Van Cleef Perlée 手链', brand: 'Van Cleef', kind: 'bracelet' },
  { id: 'j_repossé_gold_ear', label: '锤纹金耳钉', brand: '', kind: 'earring' },
  { id: 'j_bar_necklace', label: '一字横条项链', brand: '', kind: 'necklace' },
  { id: 'j_stack_rings', label: '叠戴细戒组', brand: '', kind: 'ring' },
  { id: 'j_cuff_ear', label: '耳骨夹（克制）', brand: '', kind: 'earring' },
  { id: 'j_anklet_private', label: '细金脚链（私下）', brand: '', kind: 'other' },
  { id: 'j_brooch_vintage', label: '复古胸针（大衣用）', brand: '', kind: 'other' },
  { id: 'j_locket_mini', label: '迷你锁骨吊坠', brand: '', kind: 'necklace' },
];

export const STOCK_WATCHES = [
  { id: 'w_cartier_tank', label: 'Cartier Tank Must', brand: 'Cartier', kind: 'dress' },
  { id: 'w_cartier_ballon', label: 'Cartier Ballon Bleu 小号', brand: 'Cartier', kind: 'dress' },
  { id: 'w_jlc_reverso', label: 'Jaeger-LeCoultre Reverso 女款', brand: 'Jaeger-LeCoultre', kind: 'dress' },
  { id: 'w_rolex_datejust', label: 'Rolex Datejust 31', brand: 'Rolex', kind: 'dress' },
  { id: 'w_rolex_oyster', label: 'Rolex Oyster Perpetual 28', brand: 'Rolex', kind: 'dress' },
  { id: 'w_pp_twenty4', label: 'Patek Philippe Twenty~4', brand: 'Patek Philippe', kind: 'dress' },
  { id: 'w_ap_royal_oak', label: 'Audemars Piguet Royal Oak 女款', brand: 'Audemars Piguet', kind: 'sport' },
  { id: 'w_omega_constellation', label: 'Omega Constellation', brand: 'Omega', kind: 'dress' },
  { id: 'w_iwc_portofino', label: 'IWC Portofino 女款', brand: 'IWC', kind: 'dress' },
  { id: 'w_piaget_limelight', label: 'Piaget Limelight', brand: 'Piaget', kind: 'dress' },
  { id: 'w_chanel_premiere', label: 'Chanel Première', brand: 'Chanel', kind: 'dress' },
  { id: 'w_hermes_heure', label: 'Hermès Heure H', brand: 'Hermès', kind: 'dress' },
  { id: 'w_vacheron_traditionnelle', label: 'Vacheron Constantin 传统款女表', brand: 'Vacheron Constantin', kind: 'dress' },
  { id: 'w_breguet_classique', label: 'Breguet Classique', brand: 'Breguet', kind: 'dress' },
  { id: 'w_longines_dolce', label: 'Longines DolceVita', brand: 'Longines', kind: 'dress' },
  { id: 'w_tag_aquaracer', label: 'TAG Heuer Aquaracer 女款', brand: 'TAG Heuer', kind: 'sport' },
  { id: 'w_breitling_chronomat', label: 'Breitling Chronomat 女款', brand: 'Breitling', kind: 'sport' },
  { id: 'w_apple_watch', label: 'Apple Watch 运动/机场', brand: 'Apple', kind: 'sport' },
  { id: 'w_rm_lady', label: 'Richard Mille 女款（偶尔）', brand: 'Richard Mille', kind: 'sport' },
  { id: 'w_cartier_panthere', label: 'Cartier Panthère', brand: 'Cartier', kind: 'dress' },
  { id: 'w_cartier_santos', label: 'Cartier Santos 小号', brand: 'Cartier', kind: 'dress' },
  { id: 'w_rolex_yacht', label: 'Rolex Yacht-Master 37', brand: 'Rolex', kind: 'sport' },
  { id: 'w_omega_seamaster', label: 'Omega Seamaster 女款', brand: 'Omega', kind: 'sport' },
  { id: 'w_tudor_black_bay', label: 'Tudor Black Bay 36', brand: 'Tudor', kind: 'sport' },
  { id: 'w_gucci_g_timeless', label: 'Gucci G-Timeless', brand: 'Gucci', kind: 'other' },
  { id: 'w_fendi_selleria', label: 'Fendi Selleria 表', brand: 'Fendi', kind: 'other' },
  { id: 'w_dior_la_d', label: 'Dior La D de Dior', brand: 'Dior', kind: 'dress' },
  { id: 'w_bulgari_serpenti', label: 'Bvlgari Serpenti', brand: 'Bvlgari', kind: 'dress' },
  { id: 'w_jaeger_rendez', label: 'JLC Rendez-Vous', brand: 'Jaeger-LeCoultre', kind: 'dress' },
  { id: 'w_zenith_elite', label: 'Zenith Elite 女款', brand: 'Zenith', kind: 'dress' },
  { id: 'w_nomos_tangente', label: 'NOMOS Tangente 33', brand: 'NOMOS', kind: 'other' },
];

export const STOCK_ACCESSORIES = [
  { id: 'a_hermes_carre', label: 'Hermès 真丝方巾', brand: 'Hermès', kind: 'scarf' },
  { id: 'a_hermes_shawl', label: 'Hermès / Loro 羊绒大披肩', brand: 'Hermès', kind: 'shawl' },
  { id: 'a_hermes_belt', label: 'Hermès 皮带 H 扣', brand: 'Hermès', kind: 'belt' },
  { id: 'a_celine_sunglasses', label: 'Celine 墨镜', brand: 'Celine', kind: 'sunglasses' },
  { id: 'a_chanel_sunglasses', label: 'Chanel 墨镜', brand: 'Chanel', kind: 'sunglasses' },
  { id: 'a_dior_sunglasses', label: 'Dior 墨镜', brand: 'Dior', kind: 'sunglasses' },
  { id: 'a_ysl_cat_eye', label: 'Saint Laurent 猫眼墨镜', brand: 'Saint Laurent', kind: 'sunglasses' },
  { id: 'a_baseball_cap', label: 'The Row / 极简棒球帽', brand: 'The Row', kind: 'hat' },
  { id: 'a_silk_scrunchie', label: '真丝发圈/发夹组', brand: '', kind: 'hair' },
  { id: 'a_airpods', label: 'AirPods Pro / Max', brand: 'Apple', kind: 'tech' },
  { id: 'a_glove_cashmere', label: '羊绒手套', brand: 'Loro Piana', kind: 'glove' },
  { id: 'a_lindberg_glasses', label: 'Lindberg 近视光学镜', brand: 'Lindberg', kind: 'glasses' },
  { id: 'a_cartier_gold_glasses', label: 'Cartier 金丝光学镜', brand: 'Cartier', kind: 'glasses' },
  { id: 'a_gentle_monster', label: 'Gentle Monster 墨镜', brand: 'Gentle Monster', kind: 'sunglasses' },
  { id: 'a_bottega_belt', label: 'Bottega Veneta 编织腰带', brand: 'Bottega Veneta', kind: 'belt' },
  { id: 'a_celine_belt', label: 'Celine 腰带', brand: 'Celine', kind: 'belt' },
  { id: 'a_dior_oblique_scarf', label: 'Dior 老花丝巾', brand: 'Dior', kind: 'scarf' },
  { id: 'a_chanel_camellia', label: 'Chanel 山茶花发饰', brand: 'Chanel', kind: 'hair' },
  { id: 'a_therow_hat', label: 'The Row 羊毛帽', brand: 'The Row', kind: 'hat' },
  { id: 'a_bucket_hat', label: 'Prada 尼龙渔夫帽', brand: 'Prada', kind: 'hat' },
  { id: 'a_leather_gloves', label: '小羊皮手套', brand: '', kind: 'glove' },
  { id: 'a_silk_eye_mask', label: '真丝眼罩（旅行）', brand: '', kind: 'other' },
  { id: 'a_passport_sleeve', label: '护照夹套装', brand: 'Hermès', kind: 'other' },
  { id: 'a_key_holder', label: 'Hermès 钥匙包', brand: 'Hermès', kind: 'other' },
  { id: 'a_card_holder', label: 'Chanel 卡包', brand: 'Chanel', kind: 'other' },
  { id: 'a_umbrella_luxury', label: '长柄晴雨伞', brand: '', kind: 'other' },
  { id: 'a_hair_claw_acrylic', label: '亚克力发爪夹', brand: '', kind: 'hair' },
  { id: 'a_pearl_hair_pin', label: '珍珠发簪/发夹', brand: '', kind: 'hair' },
  { id: 'a_brooch_cc', label: 'Chanel 风格胸针', brand: 'Chanel', kind: 'other' },
  { id: 'a_phone_case_luxe', label: '皮质手机壳', brand: '', kind: 'tech' },
  { id: 'a_eres_swim', label: 'Eres 泳装（度假）', brand: 'Eres', kind: 'swim' },
];

export const STOCK_LINGERIE = [
  { id: 'lg_daily_nude', label: 'La Perla 裸色无痕套装', brand: 'La Perla', kind: 'set', color: '裸' },
  { id: 'lg_daily_black', label: 'La Perla 黑色基础套装', brand: 'La Perla', kind: 'set', color: '黑' },
  { id: 'lg_eres_white', label: 'Eres 白色简约套装', brand: 'Eres', kind: 'set', color: '白' },
  { id: 'lg_sport', label: 'Lululemon 运动内衣套装', brand: 'Lululemon', kind: 'set' },
  { id: 'lg_sleep_silk', label: '真丝睡眠内衣短裤', brand: 'Olivia von Halle', kind: 'set' },
  { id: 'lg_lace_black', label: '黑色蕾丝精致套装', brand: 'Agent Provocateur', kind: 'set' },
  { id: 'lg_lace_nude', label: '裸色蕾丝套装', brand: 'La Perla', kind: 'set' },
  { id: 'lg_bodysuit', label: 'Maison Close / 高级连体', brand: '', kind: 'bodysuit' },
  { id: 'lg_hosiery_sheer', label: 'Wolford 薄透丝袜', brand: 'Wolford', kind: 'hosiery' },
  { id: 'lg_hosiery_opaque', label: 'Wolford 厚实丝袜', brand: 'Wolford', kind: 'hosiery' },
  { id: 'lg_garter', label: '吊带袜套装', brand: 'Agent Provocateur', kind: 'hosiery' },
  { id: 'lg_none', label: '真空', brand: '', kind: 'set' },
  { id: 'lg_ap_red', label: 'Agent Provocateur 深红套装', brand: 'Agent Provocateur', kind: 'set' },
  { id: 'lg_eres_black', label: 'Eres 黑色极简套装', brand: 'Eres', kind: 'set' },
  { id: 'lg_la_perla_lace_ivory', label: 'La Perla 象牙白蕾丝', brand: 'La Perla', kind: 'set' },
  { id: 'lg_seamless_grey', label: '无痕烟灰套装', brand: '', kind: 'set' },
  { id: 'lg_wireless_soft', label: '无钢圈软杯套装', brand: 'La Perla', kind: 'set' },
  { id: 'lg_push_subtle', label: '轻微聚拢日常款', brand: '', kind: 'bra' },
  { id: 'lg_bralette_silk', label: '真丝无钢圈 bralette', brand: '', kind: 'bra' },
  { id: 'lg_high_waist', label: '高腰塑形内裤', brand: '', kind: 'other' },
  { id: 'lg_boyshort', label: '平角安全裤', brand: '', kind: 'other' },
  { id: 'lg_thong_seamless', label: '无痕丁字', brand: '', kind: 'other' },
  { id: 'lg_shapewear_soft', label: '轻塑身衣（克制）', brand: '', kind: 'other' },
  { id: 'lg_slip_short', label: '防走光真丝衬裙短裤', brand: '', kind: 'other' },
  { id: 'lg_stocking_stay', label: '硅胶防滑丝袜', brand: 'Wolford', kind: 'hosiery' },
  { id: 'lg_tights_black', label: '黑色连裤袜', brand: 'Wolford', kind: 'hosiery' },
  { id: 'lg_fishnet_subtle', label: '细网袜（私下）', brand: '', kind: 'hosiery' },
  { id: 'lg_corset_soft', label: '软胸衣外穿感（克制）', brand: '', kind: 'other' },
  { id: 'lg_maternity_soft', label: '柔软无痕舒适款', brand: '', kind: 'set' },
  { id: 'lg_travel_pack', label: '旅行内衣三件套', brand: '', kind: 'set' },
  { id: 'lg_color_blush', label: '豆沙粉套装', brand: 'La Perla', kind: 'set' },
];

export const STOCK_TRAVEL = [
  { id: 'tr_rimowa_cabin', label: 'Rimowa Essential Cabin 登机箱', brand: 'Rimowa', kind: 'carryon' },
  { id: 'tr_rimowa_checkin', label: 'Rimowa Check-In L 托运', brand: 'Rimowa', kind: 'luggage' },
  { id: 'tr_tumi_compact', label: 'Tumi 商务登机箱', brand: 'Tumi', kind: 'carryon' },
  { id: 'tr_goyard_boheme', label: 'Goyard Bohème 软托特（舱内）', brand: 'Goyard', kind: 'tote' },
  { id: 'tr_rimowa_original', label: 'Rimowa Original Cabin', brand: 'Rimowa', kind: 'carryon' },
  { id: 'tr_rimowa_pilot', label: 'Rimowa Pilot 电脑箱', brand: 'Rimowa', kind: 'carryon' },
  { id: 'tr_louis_horizon', label: 'Louis Vuitton Horizon 登机', brand: 'Louis Vuitton', kind: 'carryon' },
  { id: 'tr_globe_trotter', label: 'Globe-Trotter 经典登机箱', brand: 'Globe-Trotter', kind: 'carryon' },
  { id: 'tr_away_aluminium', label: 'Away Aluminium 登机', brand: 'Away', kind: 'carryon' },
  { id: 'tr_moncler_duffle', label: 'Moncler 旅行袋', brand: 'Moncler', kind: 'tote' },
  { id: 'tr_prada_nylon_trolley', label: 'Prada 尼龙拉杆', brand: 'Prada', kind: 'carryon' },
  { id: 'tr_hermes_garden', label: 'Hermès Garden Party（舱内）', brand: 'Hermès', kind: 'tote' },
  { id: 'tr_packing_cubes', label: '高端收纳袋组', brand: '', kind: 'other' },
  { id: 'tr_laundry_bag', label: '真丝洗衣袋', brand: '', kind: 'other' },
  { id: 'tr_hangers_travel', label: '旅行衣架组', brand: '', kind: 'other' },
  { id: 'tr_steamer_mini', label: '迷你挂烫机', brand: '', kind: 'other' },
  { id: 'tr_neck_pillow_cashmere', label: '羊绒颈枕', brand: 'Loro Piana', kind: 'other' },
  { id: 'tr_eye_mask_set', label: '眼罩耳塞套装', brand: '', kind: 'other' },
  { id: 'tr_adapter_global', label: '全球转换插头', brand: '', kind: 'other' },
  { id: 'tr_power_bank', label: '轻薄充电宝', brand: '', kind: 'other' },
  { id: 'tr_document_folder', label: '证件文件夹', brand: 'Hermès', kind: 'other' },
  { id: 'tr_shoe_bags', label: '鞋子防尘袋组', brand: '', kind: 'other' },
  { id: 'tr_beauty_case', label: '化妆箱/Beauty case', brand: 'Dior', kind: 'other' },
  { id: 'tr_weekender', label: '周末旅行袋', brand: 'The Row', kind: 'tote' },
  { id: 'tr_garment_bag', label: '西装/礼服防尘衣袋', brand: '', kind: 'other' },
  { id: 'tr_rimowa_check_m', label: 'Rimowa Check-In M', brand: 'Rimowa', kind: 'luggage' },
  { id: 'tr_tumi_short_trip', label: 'Tumi Short Trip 托运', brand: 'Tumi', kind: 'luggage' },
  { id: 'tr_lv_keepall', label: 'Louis Vuitton Keepall 45', brand: 'Louis Vuitton', kind: 'tote' },
  { id: 'tr_goyard_boheme_pm', label: 'Goyard 软箱 PM', brand: 'Goyard', kind: 'luggage' },
  { id: 'tr_passport_wallet', label: '护照钱包一体', brand: 'Hermès', kind: 'other' },
  { id: 'tr_cable_kit', label: '充电线收纳包', brand: '', kind: 'other' },
];

/** 合并：已有列表优先，库存补齐到至少 minCount */
export function padWithStock(existing, stock, { minCount = 30, keyFn = (x) => (typeof x === 'string' ? x : x.label || x.id) } = {}) {
  const out = [...(existing || [])];
  const seen = new Set(out.map(keyFn).filter(Boolean).map((s) => String(s).toLowerCase()));
  for (const item of stock || []) {
    if (out.length >= minCount) break;
    const k = String(keyFn(item) || '').toLowerCase();
    if (!k || seen.has(k)) continue;
    seen.add(k);
    out.push(item);
  }
  return out;
}
